"""Update Schema

Revision ID: 1bc0a8aba0f6
Revises: 2d2a3860b08e
Create Date: 2025-07-30 22:41:56.675146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc0a8aba0f6'
down_revision: Union[str, Sequence[str], None] = '2d2a3860b08e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branchrequest', sa.Column('created_by_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_branchrequest_created_by'), table_name='branchrequest')
    op.drop_constraint(op.f('branchrequest_created_by_fkey'), 'branchrequest', type_='foreignkey')
    op.create_foreign_key(None, 'branchrequest', 'user', ['created_by_id'], ['id'])
    op.drop_column('branchrequest', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branchrequest', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'branchrequest', type_='foreignkey')
    op.create_foreign_key(op.f('branchrequest_created_by_fkey'), 'branchrequest', 'user', ['created_by'], ['id'])
    op.create_index(op.f('ix_branchrequest_created_by'), 'branchrequest', ['created_by'], unique=False)
    op.drop_column('branchrequest', 'created_by_id')
    # ### end Alembic commands ###
