"""Edit Schema

Revision ID: a410f795c844
Revises: 
Create Date: 2025-07-12 19:01:27.714362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a410f795c844'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_like_likes'), table_name='like')
    op.drop_index(op.f('ix_like_story_id'), table_name='like')
    op.drop_table('like')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('story_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('like_story_id_fkey')),
    sa.PrimaryKeyConstraint('story_id', name=op.f('like_pkey'))
    )
    op.create_index(op.f('ix_like_story_id'), 'like', ['story_id'], unique=False)
    op.create_index(op.f('ix_like_likes'), 'like', ['likes'], unique=False)
    # ### end Alembic commands ###
