"""Initial migration

Revision ID: e0036f830248
Revises:
Create Date: 2025-07-10 00:21:43.527472

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e0036f830248"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "story",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("genre", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("isRoot", sa.Boolean(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("likes", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_story_author"), "story", ["author"], unique=False)
    op.create_index(op.f("ix_story_created_at"), "story", ["created_at"], unique=False)
    op.create_index(op.f("ix_story_genre"), "story", ["genre"], unique=False)
    op.create_index(op.f("ix_story_isRoot"), "story", ["isRoot"], unique=False)
    op.create_index(op.f("ix_story_is_public"), "story", ["is_public"], unique=False)
    op.create_index(op.f("ix_story_likes"), "story", ["likes"], unique=False)
    op.create_index(op.f("ix_story_title"), "story", ["title"], unique=False)
    op.create_table(
        "branch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("src_id", sa.Integer(), nullable=False),
        sa.Column("dest_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dest_id"],
            ["story.id"],
        ),
        sa.ForeignKeyConstraint(
            ["src_id"],
            ["story.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_branch_dest_id"), "branch", ["dest_id"], unique=False)
    op.create_index(op.f("ix_branch_src_id"), "branch", ["src_id"], unique=False)
    op.create_index(op.f("ix_branch_title"), "branch", ["title"], unique=False)
    op.create_table(
        "branchrequest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("src_id", sa.Integer(), nullable=False),
        sa.Column("dest_id", sa.Integer(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dest_id"],
            ["story.id"],
        ),
        sa.ForeignKeyConstraint(
            ["src_id"],
            ["story.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_branchrequest_comment"), "branchrequest", ["comment"], unique=False
    )
    op.create_index(
        op.f("ix_branchrequest_created_at"),
        "branchrequest",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_branchrequest_dest_id"), "branchrequest", ["dest_id"], unique=False
    )
    op.create_index(
        op.f("ix_branchrequest_src_id"), "branchrequest", ["src_id"], unique=False
    )
    op.create_index(
        op.f("ix_branchrequest_status"), "branchrequest", ["status"], unique=False
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("story_id", sa.Integer(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["story.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comment_author"), "comment", ["author"], unique=False)
    op.create_index(op.f("ix_comment_content"), "comment", ["content"], unique=False)
    op.create_index(
        op.f("ix_comment_created_at"), "comment", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_comment_story_id"), "comment", ["story_id"], unique=False)
    op.create_table(
        "like",
        sa.Column("story_id", sa.Integer(), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["story.id"],
        ),
        sa.PrimaryKeyConstraint("story_id"),
    )
    op.create_index(op.f("ix_like_likes"), "like", ["likes"], unique=False)
    op.create_index(op.f("ix_like_story_id"), "like", ["story_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_like_story_id"), table_name="like")
    op.drop_index(op.f("ix_like_likes"), table_name="like")
    op.drop_table("like")
    op.drop_index(op.f("ix_comment_story_id"), table_name="comment")
    op.drop_index(op.f("ix_comment_created_at"), table_name="comment")
    op.drop_index(op.f("ix_comment_content"), table_name="comment")
    op.drop_index(op.f("ix_comment_author"), table_name="comment")
    op.drop_table("comment")
    op.drop_index(op.f("ix_branchrequest_status"), table_name="branchrequest")
    op.drop_index(op.f("ix_branchrequest_src_id"), table_name="branchrequest")
    op.drop_index(op.f("ix_branchrequest_dest_id"), table_name="branchrequest")
    op.drop_index(op.f("ix_branchrequest_created_at"), table_name="branchrequest")
    op.drop_index(op.f("ix_branchrequest_comment"), table_name="branchrequest")
    op.drop_table("branchrequest")
    op.drop_index(op.f("ix_branch_title"), table_name="branch")
    op.drop_index(op.f("ix_branch_src_id"), table_name="branch")
    op.drop_index(op.f("ix_branch_dest_id"), table_name="branch")
    op.drop_table("branch")
    op.drop_index(op.f("ix_story_title"), table_name="story")
    op.drop_index(op.f("ix_story_likes"), table_name="story")
    op.drop_index(op.f("ix_story_is_public"), table_name="story")
    op.drop_index(op.f("ix_story_isRoot"), table_name="story")
    op.drop_index(op.f("ix_story_genre"), table_name="story")
    op.drop_index(op.f("ix_story_created_at"), table_name="story")
    op.drop_index(op.f("ix_story_author"), table_name="story")
    op.drop_table("story")
    # ### end Alembic commands ###
