"""Schema design v1

Revision ID: e0b499ad5bc5
Revises: fbb52c5e6082
Create Date: 2025-07-09 23:53:31.478303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b499ad5bc5'
down_revision: Union[str, Sequence[str], None] = 'fbb52c5e6082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_age'), table_name='story')
    op.drop_index(op.f('ix_story_genre'), table_name='story')
    op.drop_index(op.f('ix_story_name'), table_name='story')
    op.drop_table('story')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('secret_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('story_pkey'))
    )
    op.create_index(op.f('ix_story_name'), 'story', ['name'], unique=False)
    op.create_index(op.f('ix_story_genre'), 'story', ['genre'], unique=False)
    op.create_index(op.f('ix_story_age'), 'story', ['age'], unique=False)
    # ### end Alembic commands ###
