"""initial models

Revision ID: fbb52c5e6082
Revises: f9a01f70173a
Create Date: 2025-07-08 22:40:36.985053

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "fbb52c5e6082"
down_revision: Union[str, Sequence[str], None] = "f9a01f70173a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "story",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("secret_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("genre", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_story_age"), "story", ["age"], unique=False)
    op.create_index(op.f("ix_story_genre"), "story", ["genre"], unique=False)
    op.create_index(op.f("ix_story_name"), "story", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_story_name"), table_name="story")
    op.drop_index(op.f("ix_story_genre"), table_name="story")
    op.drop_index(op.f("ix_story_age"), table_name="story")
    op.drop_table("story")
    # ### end Alembic commands ###
